npmPublishRegistry: "https://npm.pkg.github.com"
npmAlwaysAuth: true
npmAuthToken: "${GH_AUTH_TOKEN:-}"

npmScopes:
  "@tensor-hq/tcomp-ts":
    npmAlwaysAuth: true
    npmAuthToken: "${GH_AUTH_TOKEN:-}"
    npmRegistryServer: "https://npm.pkg.github.com"
  "@tensor-hq/tensorswap-sdk":
    npmAlwaysAuth: false
    npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@metaplex-foundation/mpl-candy-guard@*":
    dependencies:
      debug: "*"
  debug@*:
    dependencies:
      supports-color: "*"

yarnPath: .yarn/releases/yarn-3.3.1.cjs
