[features]
seeds = false
skip-lint = false

[programs.localnet]
tcomp = "TCMPhJdwDryooaGtiocG1u3xcYbRpiJzb283XfCZsDp"

[registry]
url = "https://api.apr.dev"

[[test.genesis]]
address = "BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY"
program = "./deps/metaplex-mpl/bubblegum/program/target/deploy/mpl_bubblegum.so"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./deps/metaplex-mpl/token-metadata/target/deploy/mpl_token_metadata.so"

[[test.genesis]]
address = "cmtDvXumGCrqC1Age74AVPhSRVXJMd8PJS91L8KbNCK"
program = "./deps/solana-spl/account-compression/target/deploy/spl_account_compression.so"

[[test.genesis]]
address = "noopb9bkMVfRPU8AsbpTUg8AQkHtKwMYZiFUjNRtMmV"
program = "./deps/solana-spl/account-compression/target/deploy/spl_noop.so"

[provider]
cluster = "localnet"
wallet = "tests/test-keypair.json"

[scripts]
test = "bash scripts/anchor_test.sh"
