[package]
name = "tcomp"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "tcomp"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
testing = []

[dependencies]
anchor-lang = "0.26.0"
spl-account-compression = { version="0.1.10", features = ["cpi"] }
mpl-bubblegum = {version="0.7.0", features=["cpi"]}
mpl-token-metadata = {version="1.9.1", features = [ "no-entrypoint" ]}
anchor-spl = { version = "0.26.0", features =  ["default"] }
vipers = {path= '../../lib/vipers' }
static_assertions = "1.1.0"
spl-noop = { version="0.1.3", features=["no-entrypoint"] }

# TODO: change to main branch
tensorswap = { version="1.8.0", git="ssh://git@github.com/tensor-hq/tensorswap.git", features=["cpi"], rev="7fd8417" }
