[package]
name = "tcomp"
version = "0.13.3"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "tcomp"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
testing = []

[dependencies]
tensor_nft = { version = "0.2.0", git="ssh://git@github.com/tensor-hq/tensor-common-rs.git" }
vipers = {  version="2.0.6", git="ssh://git@github.com/tensor-hq/tensor-common-rs.git" }
spl-account-compression = { version="0.1.10", features = ["cpi"] }
mpl-bubblegum = {version="0.7.0", features=["cpi"]}
mpl-token-metadata = {version="=1.8.3", features = [ "no-entrypoint" ]}
mpl-token-auth-rules = "1.2.0"
anchor-lang = "=0.26.0"
anchor-spl = { version = "=0.26.0", features =  ["default"] }
static_assertions = "1.1.0"
spl-noop = { version="0.1.3", features=["no-entrypoint"] }
tensorswap = { version = "1.8.6", git="ssh://git@github.com/tensor-hq/tensorswap.git", features=["cpi"] }
tensor_whitelist = { version="0.2.1", git="ssh://git@github.com/tensor-hq/tensorswap.git", features=["cpi"] }
