# Adapted from Anchor's GH actions file.
name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-rust:
    name: Rust Tests
    runs-on: [self-hosted, linux, x64, solana]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup/
        with:
          tswap-deploy-key: ${{ secrets.TENSORSWAP_DEPLOY_KEY }}
          tcommon-deploy-key: ${{ secrets.TENSOR_COMMON_RS_RO_DEPLOY_KEY }}

      - run: cargo build
      - run: cargo fmt -- --check
      - run: cargo clippy --all-targets -- -D warnings
      - run: cargo test

  purge-cache:
    name: Purge cache
    runs-on: [ self-hosted, linux, x64, solana]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/purge-cache/

  setup-target-build:
    name: Setup build
    runs-on: [ self-hosted, linux, x64, solana]
    # runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup/
        with:
          tswap-deploy-key: ${{ secrets.TENSORSWAP_DEPLOY_KEY }}
          tcommon-deploy-key: ${{ secrets.TENSOR_COMMON_RS_RO_DEPLOY_KEY }}

      - uses: ./.github/actions/cache-cargo/
      - run: yarn build:test
      # This ensures the IDL generated matches what's checked in!
      - uses: ./.github/actions/git-diff/

  typescript-checks:
    name: Typescript checks
    runs-on: [self-hosted, linux, x64, solana]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup/
        with:
          tswap-deploy-key: ${{ secrets.TENSORSWAP_DEPLOY_KEY }}
          tcommon-deploy-key: ${{ secrets.TENSOR_COMMON_RS_RO_DEPLOY_KEY }}

      - run: yarn build:ts
        name: Typechecks

  # ==================== Typescript test ====================

  test-typescript:
    needs: [setup-target-build]
    name: Test ${{ matrix.node.glob }}
    runs-on: [ self-hosted, linux, x64, solana]
    # runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        node:
          - glob: tests/listings.test.ts
          - glob: tests/bids.test.ts
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup/
        with:
          tswap-deploy-key: ${{ secrets.TENSORSWAP_DEPLOY_KEY }}
          tcommon-deploy-key: ${{ secrets.TENSOR_COMMON_RS_RO_DEPLOY_KEY }}

      - run: grep -Evqz 'it.only\(|describe.only\(' ${{ matrix.node.glob }}
        name: No only tests

      - uses: ./.github/actions/cache-cargo/

      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - run: yarn install
      - run: yarn fast-test
        env:
          TESTS_GLOB: ${{ matrix.node.glob }}
